FROM keydonix/geth-poa-node8-solc as builder
# TODO: use digest

RUN apk update && apk add git

COPY . /maker-docker-poa

WORKDIR /maker-docker-poa

RUN /maker-docker-poa/scripts/run-geth-and-deploy.sh

WORKDIR /


FROM keydonix/geth-poa
COPY --from=builder /geth/chain /geth/chain

# docker image build . -t keydonix/geth-poa-maker
