FROM keydonix/geth-poa-node8-solc as builder
# TODO: use digest

COPY . /maker-deployer

WORKDIR /maker-deployer

RUN /maker-deployer/scripts/run-geth-and-deploy.sh

WORKDIR /


FROM keydonix/geth-poa
COPY --from=builder /geth/chain /geth/chain

# docker image build . -t keydonix/geth-poa-maker
